version: '24.0.7'
services:
mysql:
image: mysql:5.7.29
container_name: mysql
restart: always
environmnet:
MYSQL_ROOT_PASSWORD: root
MYSQL_DATABASE: imersaofullstackefullcycle
# MYSQL_USER: root
MYSQL_PASSWORD: root
ports: 
- 3306:3306
volumes:
- .docker/mysql:/var/lib/mysql